GET http://127.0.0.1:5000/status HTTP/1.1
content-type: application/json
///
POST http://127.0.0.1:5000/insert HTTP/1.1
content-type: application/json
///
GET http://127.0.0.1:5000/all HTTP/1.1
content-type: application/json
///
GET http://127.0.0.1:5000/last HTTP/1.1
content-type: application/json
///
DELETE http://127.0.0.1:5000/delete HTTP/1.1
content-type: application/json
